services:
  - type: web
    name: visao-cliente-c6
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    autoDeploy: true
    envVars:
      - key: ADMIN_PASS
        value: "123456"
      - key: SUPERVISOR_PASS
        value: "supervisor2026"
      - key: OPERADOR_PASS
        value: "operador2026"
